name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.4.2
  share_plus: ^7.0.0
  url_launcher: ^6.2.6
  path_provider: ^2.0.14
  permission_handler: ^11.3.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # HTTP client
  http: ^1.2.1
  # Hiển thị ảnh cache từ network
  cached_network_image: ^3.3.1
  # Google Fonts cho UI đẹp
  google_fonts: ^6.2.1
  # Hiệu ứng loading
  flutter_spinkit: ^5.2.0
  # Hiển thị toast thông báo
  fluttertoast: ^8.2.4
  # Quản lý state (nếu cần)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
