name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.4.2
  share_plus: ^7.0.0
  url_launcher: ^6.2.6
  path_provider: ^2.0.14
  permission_handler: ^11.3.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false   
  image_path: "assets/icon/36cb4893-f385-4d9d-ac3a-407783828bd4.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
